import type { CourseFormData } from "@/types/course.types";

export const DEFAULT_COURSES: CourseFormData[] = [
  {
    slug: "c1",
    group: "Licencias de conducción",
    category: "Automóvil",
    badge: "Categoría C1",
    name: "Automóvil",
    subtitle: "Servicio público y particular",
    description:
      "Formación completa para conducir automóvil de servicio público y particular, integrando preparación teórica y práctica.",
    imageUrl: "/assets/images/cursos/c1.png",
    imageAlt: "Vehículo de formación categoría C1 de ReyCars",
    active: true,
    order: 1,
    price: 1450000,
    priceText: "",
    priceLabel: "Inversión",
    theoryHours: 36,
    theoryLabel: "",
    practiceHours: 30,
    practiceLabel: "",
    vehicle: "Automóvil",
    modality: "Presencial",
    durationLabel: "",
    audience: "",
    icon: "car",
    whatsappLabel: "Categoría C1 - Automóvil, servicio público y particular",
    features: [],
    includes: [
      "36 horas teóricas",
      "30 horas prácticas",
      "Servicio público y particular",
    ],
  },
  {
    slug: "a2",
    group: "Licencias de conducción",
    category: "Motocicleta",
    badge: "Categoría A2",
    name: "Motocicleta",
    subtitle: "Formación para motocicleta",
    description:
      "Preparación teórica y práctica enfocada en desarrollar control, confianza y hábitos seguros para la conducción de motocicleta.",
    imageUrl: "/assets/images/cursos/a2.png",
    imageAlt: "Motocicleta de formación categoría A2 de ReyCars",
    active: true,
    order: 2,
    price: 1030000,
    priceText: "",
    priceLabel: "Inversión",
    theoryHours: 30,
    theoryLabel: "",
    practiceHours: 15,
    practiceLabel: "",
    vehicle: "Motocicleta",
    modality: "Presencial",
    durationLabel: "",
    audience: "",
    icon: "motorcycle",
    whatsappLabel: "Categoría A2 - Motocicleta",
    features: [],
    includes: [
      "30 horas teóricas",
      "15 horas prácticas",
      "Formación en motocicleta",
    ],
  },
  {
    slug: "b1",
    group: "Licencias de conducción",
    category: "Automóvil",
    badge: "Categoría B1",
    name: "Automóvil particular",
    subtitle: "Servicio particular",
    description:
      "Proceso de formación para conducción de automóvil particular con acompañamiento teórico y práctica progresiva.",
    imageUrl: "/assets/images/cursos/b1.png",
    imageAlt: "Vehículo de formación categoría B1 de ReyCars",
    active: true,
    order: 3,
    price: 1300000,
    priceText: "",
    priceLabel: "Inversión",
    theoryHours: 32,
    theoryLabel: "",
    practiceHours: 20,
    practiceLabel: "",
    vehicle: "Automóvil",
    modality: "Presencial",
    durationLabel: "",
    audience: "",
    icon: "car",
    whatsappLabel: "Categoría B1 - Automóvil particular",
    features: [],
    includes: [
      "32 horas teóricas",
      "20 horas prácticas",
      "Servicio particular",
    ],
  },
  {
    slug: "refuerzo-auto",
    group: "Formación complementaria",
    category: "Automóvil",
    badge: "Refuerzo",
    name: "Refuerzo práctico",
    subtitle: "Automóvil",
    description:
      "Sesiones prácticas para recuperar confianza, fortalecer maniobras y trabajar necesidades específicas al volante.",
    imageUrl: "/assets/images/cursos/refuerzo-auto.png",
    imageAlt: "Refuerzo práctico en automóvil ReyCars",
    active: true,
    order: 4,
    price: null,
    priceText: "Consultar",
    priceLabel: "Valor",
    theoryHours: null,
    theoryLabel: "",
    practiceHours: null,
    practiceLabel: "Por hora",
    vehicle: "Automóvil",
    modality: "Personalizada",
    durationLabel: "Paquete de 14 horas",
    audience: "",
    icon: "steering",
    whatsappLabel: "Refuerzo práctico en automóvil",
    features: [],
    includes: [
      "Clases por hora",
      "Paquete de 14 horas",
      "Clases personalizadas",
    ],
  },
  {
    slug: "refuerzo-moto",
    group: "Formación complementaria",
    category: "Motocicleta",
    badge: "Refuerzo",
    name: "Refuerzo práctico",
    subtitle: "Motocicleta",
    description:
      "Prácticas personalizadas para mejorar dominio, maniobrabilidad y seguridad sobre la motocicleta.",
    imageUrl: "/assets/images/cursos/refuerzo-moto.png",
    imageAlt: "Refuerzo práctico en motocicleta ReyCars",
    active: true,
    order: 5,
    price: null,
    priceText: "Consultar",
    priceLabel: "Valor",
    theoryHours: null,
    theoryLabel: "",
    practiceHours: null,
    practiceLabel: "Por hora",
    vehicle: "Motocicleta",
    modality: "Personalizada",
    durationLabel: "",
    audience: "",
    icon: "motorcycle",
    whatsappLabel: "Refuerzo práctico en motocicleta",
    features: [],
    includes: [
      "Clases por hora",
      "Clases personalizadas",
      "Refuerzo de habilidades",
    ],
  },
  {
    slug: "manejo-defensivo",
    group: "Formación complementaria",
    category: "Automóvil",
    badge: "Certificado",
    name: "Manejo defensivo",
    subtitle: "Formación complementaria",
    description:
      "Formación enfocada en prevención, anticipación de riesgos y toma de decisiones responsables durante la conducción.",
    imageUrl: "/assets/images/cursos/manejo-defensivo.png",
    imageAlt: "Curso de manejo defensivo ReyCars",
    active: true,
    order: 6,
    price: null,
    priceText: "Consultar",
    priceLabel: "Valor",
    theoryHours: null,
    theoryLabel: "2 módulos",
    practiceHours: null,
    practiceLabel: "",
    vehicle: "Automóvil",
    modality: "Certificado",
    durationLabel: "",
    audience: "",
    icon: "shield",
    whatsappLabel: "Curso de manejo defensivo",
    features: [],
    includes: [
      "2 módulos",
      "Formación básica aplicada",
      "Formación teórica",
    ],
  },
  {
    slug: "refrendacion",
    group: "Formación complementaria",
    category: "Trámite",
    badge: "Refrendación",
    name: "Refrendación de licencia",
    subtitle: "Categoría individual o combo",
    description:
      "Alternativas para refrendar una categoría o gestionar un combo de categorías de manera clara y acompañada.",
    imageUrl: "/assets/images/cursos/refrendacion.png",
    imageAlt: "Refrendación de licencia ReyCars",
    active: true,
    order: 7,
    price: null,
    priceText: "Desde $345.000",
    priceLabel: "Valor",
    theoryHours: null,
    theoryLabel: "",
    practiceHours: null,
    practiceLabel: "",
    vehicle: "",
    modality: "Trámite",
    durationLabel: "",
    audience: "",
    icon: "id",
    whatsappLabel: "Refrendación de licencia",
    features: [],
    includes: [
      "1 categoría: $345.000",
      "Combo: $525.000",
      "Examen médico y derechos de impresión",
    ],
  },
];